### ISSUE TITLE
Switch to JavaScript

### ISSUE THREAD

**Issue by martindale** [maebert/themostdangerouswritingapp#1]
I really like the potential of this application.  However, your choice of CoffeeScript makes it inaccessible to a number of developers who aren't comfortable with that particular flavor of an "enhanced" JavaScript experience.

Since the application is relatively compact, it should be simple to do a one-time compile to JavaScript and migrate the project to it permanently.  Perhaps even using the new ES2015 features.  But above all else, I request that this application be switched away from CoffeeScript.

**Comment by maebert** [comment]
I'd totally love using ES6, but there's no support in IE and most mobile browsers yet. CoffeeScript adds a layer of compatibility here, and is easy enough to pick up. Since most MDWA users use older versions of InternetExplorer (they're in schools), I made the call of sacrificing ease of development over compatibility.
