### ISSUE TITLE
How to stop it when I think I have finished my paper ？

### ISSUE THREAD

**Issue by adamma1024** [maebert/themostdangerouswritingapp#36]
Why do not catch key event of `ctrl + s` ?
I had finished before 5 mins, but it can't stop.
So what should I do to finish it ?

**Comment by maebert** [comment]
Well... congratulations on finishing your paper in less than 5 minutes!

Being able to stop any time kind of defeats the purpose. Maybe using a word limit instead of a time limit helps more. If not, I recommend putting a cat on your keyboard when you're done typing but still have time left.

Exhibit a:

![Cat](https://media.tenor.com/images/7fb25f60cdc874093312215dc60265b6/tenor.gif)
